# Continuous integration: Travis CI

language: python 3.5

os: linux
dist: xenial
sudo: enabled

compiler:
   - clang

before_install:
  - sudo apt-get -qq update

# Configure git
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

install:
# Install YARP
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu xenial contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 57A5ACB6110576A6
  - sudo apt-get update
  - sudo apt-get install yarp

# Install dependencies
  - python -m pip -r install requirements.txt

before_script:
  - cd programs

script:
  - cd ..


after_success:

notifications:
email: true
